### ISSUE TITLE
Error while installing dependencies to non-ubuntu image (jenkinsci/jnlp-slave)

### ISSUE THREAD

**Issue by angusmf** [robinryf/docker-images#2]
Hi, just hoping for a little help with this if possible.  I used the 2018.1 branch.

Attempting to add Unity to a jenkins kubernetes agent by replacing FROM ubuntu in your dockerfile with
FROM jenkinsci/jnlp-slave. I'm sorta following this document under the section "Customizing the Docker Image" https://cloud.google.com/solutions/jenkins-on-kubernetes-engine

When I try to build the image, apt-get fails because of a missing folder. mkdir fails also, and sudo doesn't exist(?)  I got past this (to a new error that it can't find npm) by adding USER root to the dockerfile, but presumably that's bad. Any suggestions?

Step 2/8 : RUN apt-get -qq update && apt-get -qq install -y     git imagemagick curl gconf-service lib32gcc1 lib32stdc++6 libasound2 libc6 libc6-i386 libcairo2 libcap2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libgl1-mesa-glx libglib2.0-0 libglu1-mesa libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 zlib1g debconf npm xdg-utils lsb-release libpq5 xvfb libsoup2.4-1 libarchive13 libpng-dev python-pip python3-venv python3-pip     && rm -rf /var/lib/apt/lists/*
 ---> Running in 18ee082d6b0e
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
The command '/bin/sh -c apt-get -qq update && apt-get -qq install -y     git imagemagick curl gconf-service lib32gcc1 lib32stdc++6 libasound2 libc6 libc6-i386 libcairo2 libcap2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libgl1-mesa-glx libglib2.0-0 libglu1-mesa libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 zlib1g debconf npm xdg-utils lsb-release libpq5 xvfb libsoup2.4-1 libarchive13 libpng-dev python-pip python3-venv python3-pip     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by robinryf** [comment]
Since this is not really related to this GitHub repo I did a bit of digging. I am not completely sure but my best guess is that your new FROM statement does not bring the required features that are required for Unity.
When looking at 'jenkinsci/jnlp-slave' you can see that it is based on 'openjdk:8-jdk' which does not bring enough.

In your use case I would recommend you to not inherit from 'jenkinsci/jnlp-slave' but integrate their logic. You could use 'FROM robinryf/unity' and then add your own logic to the Dockerfile for adding the jnlp client to the image. Look at these links: https://hub.docker.com/r/jenkins/jnlp-slave/ and https://hub.docker.com/r/jenkins/slave/~/dockerfile/ to see how the jnlp agent is downloaded.

I hope this helps! 

Cheers
